services:
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # Vite dev server
      - "3001:3001"  # Express server
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - /app/client/node_modules
      - /app/server/node_modules
      - ./server/stamps.json:/app/server/stamps.json
    env_file:
      - env.dev
    networks:
      - portfolio-dev

networks:
  portfolio-dev:
    driver: bridge 