services:
  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
      - PORT=3001
      - DOMAIN=dana.nyc
      - RATE_LIMIT_WINDOW=60000
      - RATE_LIMIT_MAX_REQUESTS=100
      - PASSWORD_HASH=f0713226878b7bcabee80b1f86f0685055f9d12616bdf8ec46fc3c1372d29ec2
      - JWT_SECRET=f0df9c6c8c7fda46de65e9943755839a9fad612c58cf465dd47d3ed4d00e6580badd58c2555b25529769f540a5bed315a576cd4d692eb44b182ab42b0840c0f0
      - ADMIN_KEY=529d31086219a3b4df5b7b8b593d9111757304864bbfd9aa9bff9bded19023a4
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs:/var/log/nginx
      - ./server/stamps.json:/app/server/stamps.json
    networks:
      - portfolio-prod
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  portfolio-prod:
    driver: bridge 